#!/bin/sh

make clean
make
make stage
make check-plist
file work/check_reload_status-0.0.18/check_reload_status
ldd work/check_reload_status-0.0.18/check_reload_status
make package
pkg info -F work/pkg/check_reload_status-0.0.18.pkg
pkg info -F work/pkg/check_reload_status-0.0.18.pkg -l
